parameters:
  - name: architectures
    type: object

stages:
  - ${{ each arch in parameters.architectures }}:
      - stage: "${{ arch }}"
        dependsOn: Prepare
        jobs:
          - job: Build
            steps:
              - template: install.yml
              - script: >
                  containmint build
                  --tag "quay.io/ansible/scratchpad:$(ContainerName)-${{ arch }}"
                  --arch "${{ arch }}"
                  --context "$(ContainerName)"
                  $(push_or_no_login)
                displayName: Build
                env:
                  CONTAINMINT_PASSWORD: $(CONTAINMINT_PASSWORD)
            strategy:
              matrix: $[ stageDependencies.Prepare.Matrix.outputs['Generate.containers'] ]
